### ISSUE TITLE
removing leading slash from saved key

### ISSUE THREAD

**Issue by sean-roberts** [mxstbr/micro-analytics#27]
so when I GET:

`service.com/test` it will store `{ "/test": {...} }`

I was experimenting with using grafana like namespaces for metrics like `name.space.id.a.metric` and the only thing that gets in the way is the leading slash.

so 
`service.com/extension.chrome.installed` it will store `{ "/extension.chrome.installed": {...} }`

My feeling is that, even if you are wanting to use the paths for tracking, it's a bit redundant to have that leading slash.

**Comment by mxstbr** [comment]
This is a breaking change, as any people using `micro-analytics` now who update will lose all of their data :cry:

Let's leave this is as-is for now, and do it together with the `views -> counts` thing mentioned in #22!
